terminate called after throwing an instance of 'std::runtime_error'
  what():  Variable bnot declared

Aborted (core dumped)

exit status: 134
