terminate called after throwing an instance of 'std::runtime_error'
  what():  Red√©claration d'une variable
Aborted (core dumped)

exit status: 134
